spring:
  main:
    web-application-type: reactive
  application:
    name: domain
  cloud:
    gateway:
      routes:
        - id: user-api
          uri: http://localhost:8081
          predicates:
            - Path=/users/**,/sellers/**
          filters:
            - name: JwtAuthFilter

        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/oauth/**

        - id: order-api
          uri: http://localhost:8082
          predicates:
            - Path=/order-api/**
          filters:
            - JwtAuthFilter

jwt:
  secret-key: c2VjcmV0LWtleS1mb3Itc3RyYXktY2F0LW1hcC0yMDI0LTEyLTE3

logging:
  level:
    org:
      springframework: DEBUG